'use strict';

const { getBotName } = require('../../lib/botname');

function randomCode() {
return String(
Math.floor(100000 + Math.random() * 900000)
);
}

module.exports = {

name: 'receivecode',

aliases: [
    'getcode',
    'verifycode',
    'smscode'
],

description:
    'Generate a fictional verification code for testing',

category: 'utility',

async execute(
    sock,
    msg,
    args,
    prefix
) {

    const jid =
        msg.key.remoteJid;

    const botName =
        getBotName();

    const p =
        prefix || '.';

    const number =
        String(args?.[0] || '')
            .trim();

    /*
    |--------------------------------------------------------------------------
    | NUMBER CHECK
    |--------------------------------------------------------------------------
    */

    if (!number) {

        return sock.sendMessage(
            jid,
            {
                text:

"┏━━❐ 📩 RECEIVE CODE ❐ ┃ ┃ ❌ Number required ┃ ┃ Usage: ┃ ${p}receivecode +234XXXXXXXXXX ┃ ┃ Example: ┃ ${p}receivecode +2348012345678 ┃ ┗━━❐ ⚡ ${botName}"
},
{ quoted: msg }
);

    }

    /*
    |--------------------------------------------------------------------------
    | BASIC NUMBER VALIDATION
    |--------------------------------------------------------------------------
    */

    if (!/^\+\d{7,15}$/.test(number)) {

        return sock.sendMessage(
            jid,
            {
                text:

"┏━━❐ 📩 RECEIVE CODE ❐ ┃ ┃ ❌ Invalid number format ┃ ┃ Use international format: ┃ ${p}receivecode +2348012345678 ┃ ┗━━❐ ⚡ ${botName}"
},
{ quoted: msg }
);

    }

    /*
    |--------------------------------------------------------------------------
    | GENERATE DEMO CODE
    |--------------------------------------------------------------------------
    */

    const code =
        randomCode();

    /*
    |--------------------------------------------------------------------------
    | REACTION
    |--------------------------------------------------------------------------
    */

    try {

        await sock.sendMessage(
            jid,
            {
                react: {
                    text: '📩',
                    key: msg.key
                }
            }
        );

    } catch {}

    /*
    |--------------------------------------------------------------------------
    | RESPONSE
    |--------------------------------------------------------------------------
    */

    return sock.sendMessage(
        jid,
        {
            text:

`╭━━━〔 📩 RECEIVE CODE 〕━━━╮
┃
┃ ☎️ Number : ${number}
┃
┃ 🔐 Code   : ${code}
┃
┃ 📡 Status : Generated
┃
╰━━━━━━━━━━━━━━━━━━━━╯

╭━━━〔 ⚠️ DEMO MODE 〕━━━╮
┃
┃ This is a fictional test code
┃ generated by ${botName}.
┃
┃ It is NOT retrieved from SMS
┃ and cannot verify a real account.
┃
╰━━━━━━━━━━━━━━━━━━━━╯

⚡ Powered by ᴄʜʀɪꜱ ɢᴀᴀᴊᴜ`
},
{ quoted: msg }
);

}

};
